name       : libquotient
version    : 0.7.2
release    : 7
source     :
    - https://github.com/quotient-im/libQuotient/archive/refs/tags/0.7.2.tar.gz : 62ff42c8fe321e582ce8943417c1d815ab3f373a26fa0d99a5926e713f6a9382
homepage   : https://matrix.org/docs/projects/sdk/quotient
license    : LGPL-2.1-or-later
component  : programming.library
summary    : A Qt library to write cross-platform clients for Matrix
description: |
    A Qt library to write cross-platform clients for Matrix
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Sql)
    - pkgconfig(libcrypto)
    - pkgconfig(olm)
    - qtkeychain-devel
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON -DQuotient_ENABLE_E2EE=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove android bits
    rm -rf $installdir/usr/share
