name       : libquotient
version    : 0.7.1
release    : 4
source     :
    - https://github.com/quotient-im/libQuotient/archive/refs/tags/0.7.1.tar.gz : 48b15c666528405219ff0be8f0f336405c64deb1719115af75ef099cb3f86555
homepage   : https://matrix.org/docs/projects/sdk/quotient
license    : LGPL-2.1-or-later
component  : programming.library
summary    : A Qt library to write cross-platform clients for Matrix
description: |
    A Qt library to write cross-platform clients for Matrix
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - qtkeychain-devel
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove android bits
    rm -rf $installdir/usr/share
