name       : libquotient
version    : 0.6.6
release    : 2
source     :
    - https://github.com/quotient-im/libQuotient/archive/refs/tags/0.6.6.tar.gz : 33d3da5a7045bbe2611dd73104279986dd8356b24de339dd10874c1a9417bba7
homepage   : https://matrix.org/docs/projects/sdk/quotient
license    : LGPL-2.1-or-later
component  : programming.library
summary    : A Qt library to write cross-platform clients for Matrix
description: |
    A Qt library to write cross-platform clients for Matrix
builddeps  :
    - pkgconfig(Qt5Multimedia)
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove android bits
    rm -rf $installdir/usr/share
