name       : libquotient
version    : 0.6.11
release    : 3
source     :
    - https://github.com/quotient-im/libQuotient/archive/refs/tags/0.6.11.tar.gz : 12b15d1296e630477d5e8f4d32c821dc724b3c5b99d15d383417ba7d88f03c46
homepage   : https://matrix.org/docs/projects/sdk/quotient
license    : LGPL-2.1-or-later
component  : programming.library
summary    : A Qt library to write cross-platform clients for Matrix
description: |
    A Qt library to write cross-platform clients for Matrix
builddeps  :
    - pkgconfig(Qt5Multimedia)
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove android bits
    rm -rf $installdir/usr/share
