name       : libquotient
version    : 0.6.4
release    : 1
source     :
    - https://github.com/quotient-im/libQuotient/archive/0.6.4.tar.gz : 4c43a68c144d41e3826f2e1ce006760129694b79d8d7f302dea81328c6a663ce
homepage   : https://matrix.org/docs/projects/sdk/quotient
license    : LGPL-2.1-or-later
component  : programming.library
summary    : A Qt library to write cross-platform clients for Matrix
description: |
    A Qt library to write cross-platform clients for Matrix
builddeps  :
    - pkgconfig(Qt5Multimedia)
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove android bits
    rm -rf $installdir/usr/share
